//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Direccions = new HashSet<Direccion>();
            this.Prestamos = new HashSet<Prestamo>();
            this.Referencias = new HashSet<Referencia>();
            this.Telefonoes = new HashSet<Telefono>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Identificacion { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<int> Genero { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
        public Nullable<int> Profesion { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public string Apodo { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Cliente Cliente2 { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual EstadoCivil EstadoCivil1 { get; set; }
        public virtual Genero Genero1 { get; set; }
        public virtual Identificacion Identificacion1 { get; set; }
        public virtual Profesion Profesion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referencia> Referencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefono> Telefonoes { get; set; }
    }
}
