//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> ReferenciaId { get; set; }
        public Nullable<int> TipoDireccion { get; set; }
        public string Calle { get; set; }
        public string Esquina { get; set; }
        public string Numero { get; set; }
        public string Edificio { get; set; }
        public string Residencial { get; set; }
        public string Piso { get; set; }
        public string Apartamento { get; set; }
        public string Color { get; set; }
        public string Urbanizacion { get; set; }
        public Nullable<int> CiudadId { get; set; }
        public string RefCercana { get; set; }
        public Nullable<int> ProvinciaId { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual Referencia Referencia { get; set; }
    }
}
