//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.ViaDesembolsoes = new HashSet<ViaDesembolso>();
        }
    
        public int PrestamoId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> TipoPrestamoId { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public Nullable<decimal> MontoPrestamo { get; set; }
        public Nullable<decimal> Tasa { get; set; }
        public Nullable<decimal> Cuota { get; set; }
        public Nullable<int> CantCuotas { get; set; }
        public Nullable<decimal> Capital { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public Nullable<decimal> BalanceCorriente { get; set; }
        public Nullable<decimal> BalanceTermino { get; set; }
        public Nullable<decimal> MontoAtraso { get; set; }
        public Nullable<int> CuotasAtrasadas { get; set; }
        public Nullable<System.DateTime> FechaultimoPago { get; set; }
        public Nullable<decimal> MontoUltimoPago { get; set; }
        public Nullable<int> EstadoCuenta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual PrestamoTipo PrestamoTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViaDesembolso> ViaDesembolsoes { get; set; }
    }
}
