//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> ReferenciaId { get; set; }
        public Nullable<int> TipoTelefono { get; set; }
        public string Telefono1 { get; set; }
        public string Extension { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Referencia Referencia { get; set; }
        public virtual TelefonoTipo TelefonoTipo { get; set; }
    }
}
