//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViaDesembolso
    {
        public int DesembolsoId { get; set; }
        public Nullable<int> BancoId { get; set; }
        public Nullable<int> ViaTipoId { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> MontoDesembolso { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> PrestamoId { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Prestamo Prestamo { get; set; }
        public virtual ViaTipo ViaTipo { get; set; }
    }
}
